apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "serabut.nadName" . }}
  labels:
    {{- include "serabut.labels" . | nindent 4 }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "{{ .Values.network.interface }}",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp"
      }
    }
